### ISSUE TITLE
error with removing public from laravel url

### ISSUE THREAD

**Issue by rebornishard** [kiberzauras/laravel.multilanguage#3]
Hello sir,
cheers for great package

btw i got error for this url

{!! URL::to('public/images/image1.png') !!}
this will echo
http://test.com/en/public/images/image1.png
is there any safer way to ignore 'en' for some url (css, js, images, font)

how i remove public url :
i cut .htaccess from public folder,
paste it to root folder
rename server.php to index.php

thank you

---

solved using assets
https://laravel.com/docs/5.1/helpers#method-asset

please add in readme
thanks

**Comment by kiberzauras** [comment]
#4

**Comment by grinry** [comment]
Hi @rebornishard ,

I wouldn't suggest you to use root folder as your script landing because of security.
For shared hosting you can add fallowing code to your `public/index.php`

```
$app = require_once __DIR__.'/../bootstrap/app.php';
$app->bind('path.public', function() {
    return __DIR__;
});
```

This way you will be able to change your `public` folder name to whenever you want: `www`, `public_html` etc.

And yes, using #4 `asset('images/logo.png')` is the right way of accessing public assets.
